version: '3.1'

services:

  projeto-app-nginx:
    build:
      context: app-nginx/
    volumes:
      - ../../client/dist:/usr/share/nginx/html/projeto-frontend
    ports:
      - "8080:8080"
    networks:
      projeto-net:
        aliases:
          - projeto-nginx

  server:
    environment:
      AMBIENTE: "${AMBIENTE:-dev}"
    build:
      context: server/
    ports:
      - "9000:8000"
    volumes:
      - ../..:/usr/src/app
    networks:
      projeto-net:
        aliases:
          - projeto-server

networks:
  projeto-net: null
